sections:
- commits:
  - 0001-chg-usr-58-Merge-Local-changes-from-earlier-version-.patch
  - 0002-usr-chg-Fix-DataContext-for-Date-type-used-for-check.patch
  - 0005-chg-dev-62-Support-hive-built-in-methods-to_date-uni.patch
  - 0006-new-usr-63-Add-support-for-hive-operators-and-consta.patch
  name: unclassified
tracking:
  branch: qds-1.13rc
  commit-id: 6d0a7a00ad554466a18e453ef3a989db425c9d0f 
version: 1
